### PR TITLE
Ability to customize notification icon on android

### PR DESCRIPTION
**Pull request by derekcaneja**
The drawer item opens the application when clicked.

### CODE REVIEW

**Comment by christocracy** [comment]
Another problem:  there's PR that came in before yours which appends another Android config param #postLocationsToServer
https://github.com/christocracy/cordova-plugin-background-geolocation#example-application

**Comment by derekcaneja** [comment]
Okay, I can fix that. Should I wait until #123 is merged, rebase, and then fix it?

**Comment by christocracy** [comment]
Yea, please wait.

On Mon, Jan 26, 2015 at 1:56 PM, Derek Caneja <notifications@github.com>
wrote:

> Okay, I can fix that. Should I wait until #123
> <https://github.com/christocracy/cordova-plugin-background-geolocation/pull/123>
> is merged, rebase, and then fix it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/pull/135#issuecomment-71515664>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by dbaq** [comment]
thanks @derekcaneja

**Comment by derekcaneja** [comment]
@dbaq No problem!  Please be aware of the problem which @christocracy had brought up in the comments above.  I am working to make a fix.

**Pull request closed without merging**
